<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 */

?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
        	<?php echo $this->__('Verrai rediretto al sito di Pagonline Unicredit'); ?>
        </li>
    </ul>
</fieldset>
